package seminar;

import seminar.database.DatabaseManager;
import seminar.database.dao.*;
import seminar.models.*;
import seminar.models.enums.*;

public class App {
    public static void main(String[] args) {
        // Initialize database
        DatabaseManager dbManager = DatabaseManager.getInstance();
        dbManager.initializeDatabase();

        // Test creating a student
        Student student = new Student("user1", "pass123", "John Doe",
                "john@example.com", "S001");
        StudentDAO studentDAO = new StudentDAO();
        boolean created = studentDAO.createStudent(student);

        if (created) {
            System.out.println("Student created successfully with ID: " + student.getUserId());
        }

        // Close connection when done
        dbManager.closeConnection();
    }
}

// /*
// * This source file was generated by the Gradle 'init' task
// */
// package seminar;

// public class App {
// public String getGreeting() {
// return "Hello World!";
// }

// public static void main(String[] args) {
// System.out.println(new App().getGreeting());
// }
// }