/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */
import org.gradle.api.tasks.Delete

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.gradleup.shadow") version "9.3.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

    implementation("org.xerial:sqlite-jdbc:3.45.1.0")
    implementation("org.slf4j:slf4j-simple:2.0.7")
    implementation("com.toedter:jcalendar:1.4")
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "seminar_manager.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}


tasks.register<JavaExec>("seedDb") {
    group = "application"
    description = "Seed the database with test data"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "seminar_manager.SeedDb"
    
    // Optional: Show output in console
    standardInput = System.`in`
    standardOutput = System.out
}

tasks.register<Delete>("cleanDb") {
    group = "build"
    description = "Delete the database file"
    
    // Correct way to specify files to delete
    delete("seminar_management.db")
    
    doLast {
        println("Database file deleted (if it existed)")
    }
}

tasks.register("cleanSeedDb") {
    group = "application"
    description = "Clean the database and then seed it with test data"

    dependsOn("cleanDb", "seedDb")
}

tasks.named("seedDb") {
    mustRunAfter("cleanDb")
}

tasks.shadowJar {
    archiveBaseName.set("seminar_manager")
    archiveClassifier.set("")
    archiveVersion.set("")
}