/*
 * This source file was generated by the Gradle 'init' task
 */
package parking_lot_management_system;

import javax.swing.SwingUtilities;

import parking_lot_management_system.views.MainFrame;

public class App {
    // public String getGreeting() {
    // return "Hello World!";
    // }

    // public static void main(String[] args) {
    // System.out.println(new App().getGreeting());
    // }
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new MainFrame());
    }
}
